# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20170810_0551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldofresearch',
            options={'ordering': ['code'], 'verbose_name_plural': 'Fields of Research'},
        ),
        migrations.AlterModelOptions(
            name='labelsalias',
            options={'verbose_name_plural': 'Alias'},
        ),
        migrations.AlterUniqueTogether(
            name='ingest',
            unique_together=set([('extraction_date', 'collection', 'storage_product')]),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set([('value', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='labelsalias',
            unique_together=set([('label', 'value')]),
        ),
        migrations.AddIndex(
            model_name='ingest',
            index=models.Index(fields=['collection', 'storage_product', 'extraction_date'], name='application_collect_4c6fef_idx'),
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['group', 'value'], name='labels_labe_group_i_ce115f_idx'),
        ),
        migrations.AddIndex(
            model_name='labelsalias',
            index=models.Index(fields=['label'], name='labels_alia_label_i_e668d5_idx'),
        ),
    ]
