# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20170811_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suborganization',
            options={'verbose_name': 'Suborganization'},
        ),
        migrations.AlterField(
            model_name='organisation',
            name='rifcs_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Notification Email Address'),
        ),
    ]
