# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20170811_0350'),
    ]

    operations = [
        migrations.RenameField('Domain', 'fieldofresearch', 'field_of_research'),
    ]
