# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import storage.models.labels


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20170816_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='idm_domain',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('IDM Domain'), help_text='???', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='allocation_idm_domain', to='storage.Label'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='operational_center',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Operational Center'), help_text='the operational center', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='allocation_op_center', to='storage.Label'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='site',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Data Center'), help_text='the storage site', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='allocation_site', to='storage.Label'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Allocation Status'), help_text='the status of this allocation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='allocation_status', to='storage.Label', verbose_name='allocation status'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Position'), help_text='the contacts position at that organisation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_position', to='storage.Label', verbose_name='Organisation Position'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Title'), help_text='the contacts title', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_title', to='storage.Label', verbose_name='Contact Title'),
        ),
        migrations.AlterField(
            model_name='custodian',
            name='role',
            field=models.ForeignKey(default=storage.models.labels.GroupDefaultLabel('Custodian Role'), help_text='the role of this custodian', on_delete=django.db.models.deletion.DO_NOTHING, related_name='custodian_role', to='storage.Label', verbose_name='Custodian Role'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.ForeignKey(default=storage.models.labels.GroupDefaultLabel('Organisation'), help_text='the full name for the organisation', on_delete=django.db.models.deletion.DO_NOTHING, related_name='organisation_name', to='storage.Label'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='rifcs_email',
            field=models.EmailField(blank=True, help_text='the RIFCS contact email address for the organisation', max_length=254, null=True, verbose_name='Notification email address'),
        ),
        migrations.AlterField(
            model_name='project',
            name='collective',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Collective'), help_text='???', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collection_collective', to='storage.Label'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Collection Status'), help_text='the collection status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collection_status', to='storage.Label'),
        ),
        migrations.AlterField(
            model_name='request',
            name='capital_funding_source',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Funding Code'), help_text='where the funding for the collection is being sourced from', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_cap_funding_source', to='storage.Label'),
        ),
        migrations.AlterField(
            model_name='request',
            name='institution_faculty',
            field=models.ForeignKey(blank=True, help_text='the UoM Faculty this request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_suborganization', to='storage.Suborganization'),
        ),
        migrations.AlterField(
            model_name='request',
            name='node',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Node'), help_text='VicNode or not?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Application_Node', to='storage.Label', verbose_name='target node'),
        ),
        migrations.AlterField(
            model_name='request',
            name='scheme',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Allocation Scheme'), help_text='the scheme to be used for the collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_allocation_scheme', to='storage.Label', verbose_name='allocation scheme'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Application Status'), help_text='where the request is in its lifecycle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_status', to='storage.Label', verbose_name='application status'),
        ),
        migrations.AlterField(
            model_name='storageproduct',
            name='operational_center',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Operational Center'), help_text='this products operational center', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='storage_product_op_center', to='storage.Label'),
        ),
        migrations.AlterField(
            model_name='storageproduct',
            name='product_name',
            field=models.ForeignKey(default=storage.models.labels.GroupDefaultLabel('Storage Product'), help_text='the name of this storage product', on_delete=django.db.models.deletion.DO_NOTHING, related_name='storageproduct_name', to='storage.Label'),
        ),
        migrations.AlterField(
            model_name='storageproduct',
            name='scheme',
            field=models.ForeignKey(default=storage.models.labels.GroupDefaultLabel('Allocation Scheme'), help_text='the allocation scheme for this product', on_delete=django.db.models.deletion.DO_NOTHING, related_name='storageproduct_allocation_scheme', to='storage.Label'),
        ),
    ]
