# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20170818_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='institution_faculty',
            field=models.ForeignKey(blank=True, help_text='the UoM Faculty this request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_suborganization', to='storage.Suborganization'),
        ),
    ]
