# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20170818_0608'),
    ]

    operations = [
        migrations.RenameField('Request', 'institution_faculty', 'faculty'),
    ]
