# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 06:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('storage', '0012_auto_20170821_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLayer',
            fields=[
                ('id', models.AutoField(
                    help_text='the primary key',
                    primary_key=True, serialize=False)),
                ('description', models.CharField(
                    help_text='the manner in which the data is to be accessed',
                    max_length=200)),
                ('creation_date', models.DateField(
                    auto_now_add=True, verbose_name='record creation date',
                    null=True)),
                ('last_modified', models.DateField(
                    auto_now=True, verbose_name='date last modified',
                    null=True)),
                ('active_flag', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(
                    related_name='applications_accesslayer_created',
                    blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('source', models.ForeignKey(
                    related_name='access_layer_source', default=None,
                    blank=True, to='storage.Label', null=True,
                    verbose_name='access layer source')),
                ('updated_by', models.ForeignKey(
                    related_name=b'applications_accesslayer_updated',
                    blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'db_table': 'applications_accesslayer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccessLayerMember',
            fields=[
                ('id', models.AutoField(help_text='the primary key',
                                        primary_key=True, serialize=False)),
                ('collection', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='collections', to='storage.Collection'),),
                ('accesslayer', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='accesslayer', to='storage.AccessLayer'), ),
            ],
            options={
                'db_table': 'access_layer_member',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='custodian',
            name='collection',
            field=models.ForeignKey(
                help_text='the collection this custodian is associated with',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='custodians', to='storage.Collection'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='collection',
            field=models.ForeignKey(help_text='the associated collection',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='domains',
                                    to='storage.Collection'),
        ),
        migrations.AlterField(
            model_name='request',
            name='faculty',
            field=models.ForeignKey(blank=True, db_column='faculty_id',
                                    help_text='the Faculty this request belongs to',
                                    null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='application_suborganization',
                                    to='storage.Suborganization'),
        ),
    ]
