# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_auto_20170912_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslayer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accesslayermember',
            options={},
        ),
    ]
