# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import storage.models.labels


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_auto_20170914_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslayer',
            name='active_flag',
        ),
        migrations.RemoveField(
            model_name='accesslayer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='accesslayer',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='accesslayer',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='accesslayer',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='accesslayer',
            name='source',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Access Layer Source'), help_text='the access layer source', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='access_layer', to='storage.Label'),
        ),
    ]
