# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import storage.models.labels


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_auto_20170914_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='link',
            field=models.URLField(blank=True, default='', help_text='a link to the collection', null=True),
        ),
        migrations.AlterField(
            model_name='accesslayermember',
            name='accesslayer',
            field=models.ForeignKey(default=1, help_text='the access layer this collection is associated with', on_delete=django.db.models.deletion.DO_NOTHING, related_name='accesslayer', to='storage.AccessLayer'),
        ),
        migrations.AlterField(
            model_name='accesslayermember',
            name='collection',
            field=models.ForeignKey(default=1, help_text='the collection this access layer is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='storage.Collection'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='idm_domain',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('IDM Domain'), help_text='the identity management domain (idm)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='allocation_idm_domain', to='storage.Label'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='idm_identifier',
            field=models.CharField(blank=True, help_text='the identifier within the idm domain', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collective',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Collective'), help_text='legacy funding and is based on research domains', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collection_collective', to='storage.Label'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='overview',
            field=models.TextField(blank=True, help_text='summary notes on the collection', null=True),
        ),
        migrations.AlterField(
            model_name='collectionprofile',
            name='merit_justification',
            field=models.TextField(blank=True, help_text='description of what the collection is', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, help_text='the contacts non-business phone number', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='used_replica',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='??', max_digits=15, null=True, verbose_name='the replica storage used (if any) in GB'),
        ),
        migrations.AlterField(
            model_name='ingestfile',
            name='location',
            field=models.SmallIntegerField(choices=[(1, 'Clayton'), (2, 'Queensbury'), (3, 'Noble Park')], db_column='file_location', help_text='the data hall'),
        ),
        migrations.AlterField(
            model_name='request',
            name='capital_funding_source',
            field=models.ForeignKey(blank=True, default=storage.models.labels.GroupDefaultLabel('Funding Code'), help_text='the funding scheme for the collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_cap_funding_source', to='storage.Label'),
        ),
        migrations.AlterField(
            model_name='request',
            name='faculty',
            field=models.ForeignKey(blank=True, db_column='faculty_id', help_text='the Faculty this request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_suborganization', to='storage.Suborganization'),
        ),
    ]
