# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_auto_20171115_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionprofile',
            name='merit_justification',
            field=models.TextField(blank=True, db_column='merit_justification', help_text='description of what the collection is', null=True, verbose_name='Description'),
        ),
    ]
