# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_auto_20171206_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestfile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='used_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='the ingested capacity in GB', max_digits=15, null=True, verbose_name='ingested capacity in GB'),
        ),
        migrations.AlterField(
            model_name='request',
            name='faculty',
            field=models.ForeignKey(blank=True, db_column='faculty_id', help_text='the Faculty this request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_suborganization', to='storage.Suborganization'),
        ),
        migrations.AlterField(
            model_name='request',
            name='scheme',
            field=models.ForeignKey(blank=True, help_text='the scheme to be used for the collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_allocation_scheme', to='storage.Label', verbose_name='allocation scheme'),
        ),
    ]
