# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_auto_20180206_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='faculty',
            field=models.ForeignKey(blank=True, db_column='faculty_id', help_text='the Faculty this request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_suborganization', to='storage.Suborganization'),
        ),
    ]
