# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0019_auto_20180206_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestCollectionError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collKey', models.TextField()),
                ('spKey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IngestFileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.SmallIntegerField()),
                ('line_text', models.TextField()),
                ('error', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestFileRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.TextField(null=True)),
                ('process_date', models.DateTimeField(auto_now_add=True, verbose_name='Ingest run time stamp')),
                ('run_error', models.TextField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_runs', to='storage.IngestFile')),
            ],
        ),
        migrations.AddField(
            model_name='ingestfiledata',
            name='ingest_parent_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_results', to='ingest.IngestFileRun'),
        ),
        migrations.AddField(
            model_name='ingestcollectionerror',
            name='ingestFileRun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_errors', to='ingest.IngestFileRun'),
        ),
        migrations.AddField(
            model_name='ingestcollectionerror',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingest_errors', to='storage.StorageProduct'),
        ),
    ]
