# Juno Release
heat_template_version: 2014-10-16


description: 'Make a trove database instance for this server'


parameters:
  availability_zone:
    type: string
    label: Availability Zone
    description: Physical location of the server.
    default: melbourne-qh2

  store_id:
    type: string
    label: Store ID
    description: ID of datastore on trove to use.

  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (trove-flavor) to be used.

  size_gb:
    type: number
    label: Size GB
    description: Size of storage for instance

resources:

  database:
    type: OS::Trove::Instance
    properties:
      availability_zone: { get_param: availability_zone }
      datastore_type: { get_param: store_id }
      flavor: { get_param: instance_type }
      size: { get_param: size_gb }
      

outputs:
    instance_ip:
        description: The IP address of the deployed instance
        value: { get_attr: [database, show, ip, 0] }

    instance_name:
        description: The name of the deployed instance
        value: { get_attr: [database, show, name] }
